"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['phyloGenerator.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True}

print "COPY THE REQUIRES FOLDER IN"
print "COPY THE REQUIRES FOLDER IN"
print "COPY THE REQUIRES FOLDER IN"


setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)


print "COPY THE REQUIRES FOLDER IN"
print "COPY THE REQUIRES FOLDER IN"
print "COPY THE REQUIRES FOLDER IN"